-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO Course VALUES (1, 'FRONT-END DEVELOPER');
INSERT INTO Course VALUES (2, 'FULL-STACK DEVELOPER');
INSERT INTO Course VALUES (3, 'BACK-END DEVELOPER');

INSERT INTO Lecture VALUES (1, 'JS', '10:00-11.45', 1);
INSERT INTO Lecture VALUES (2, 'REACT', '12:00-13.45', 1);
INSERT INTO Lecture VALUES (3, 'ANGULAR', '14:00-15.45', 1);
INSERT INTO Lecture VALUES (4, 'JAVA', '10:00-11.45', 2);
INSERT INTO Lecture VALUES (5, 'SPRING BOOT', '12:00-13.45', 2);
INSERT INTO Lecture VALUES (6, '.NET', '14:00-15.45', 2);
INSERT INTO Lecture VALUES (7, 'MYSQL', '10:00-11.45', 3);
INSERT INTO Lecture VALUES (8, 'MONGODb', '12:00-13.45', 3);
INSERT INTO Lecture VALUES (9, 'GRAPH SQL', '14:00-15.45', 3);

INSERT INTO USER VALUES (1, 'user1@gmail.com', 'user1');
INSERT INTO USER VALUES (2, 'user2@gmail.com', 'user2');
INSERT INTO USER VALUES (3, 'user3@gmail.com', 'user3');
INSERT INTO USER VALUES (4, 'user4@gmail.com', 'user4');
INSERT INTO USER VALUES (5, 'user5@gmail.com', 'user5');
INSERT INTO USER VALUES (6, 'user6@gmail.com', 'user6');
INSERT INTO USER VALUES (7, 'user7@gmail.com', 'user7');
INSERT INTO USER VALUES (8, 'user8@gmail.com', 'user8');
INSERT INTO USER VALUES (9, 'user9@gmail.com', 'user9');
INSERT INTO USER VALUES (10, 'user10@gmail.com', 'user10');

INSERT INTO USER_LECTURE VALUES (1,1);
INSERT INTO USER_LECTURE VALUES (1,5);
INSERT INTO USER_LECTURE VALUES (1,9);
INSERT INTO USER_LECTURE VALUES (2,1);
INSERT INTO USER_LECTURE VALUES (3,1);
INSERT INTO USER_LECTURE VALUES (4,1);
INSERT INTO USER_LECTURE VALUES (5,1);
INSERT INTO USER_LECTURE VALUES (6,3);
INSERT INTO USER_LECTURE VALUES (6,4);
INSERT INTO USER_LECTURE VALUES (6,5);
INSERT INTO USER_LECTURE VALUES (7,2);
INSERT INTO USER_LECTURE VALUES (8,7);
INSERT INTO USER_LECTURE VALUES (9,8);
INSERT INTO USER_LECTURE VALUES (10,6);








